### ISSUE TITLE
Accessing package causes ascii decoding error

### ISSUE THREAD

**Issue by saksham219** [quiltdata/quilt#1929]
While using quilt3 3.2.1 for browsing a package that was creating using 3.1.2, I get an ascii decoding error.

```
quilt_pkg = quilt3.Package.browse("test_package/data", quilt_s3_bucket)
Downloading manifest: 100%|##############################################################| 41.6k/41.6k [00:01<00:00, 23.6kB/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/quilt3/telemetry.py", line 132, in decorated
    results = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/quilt3/packages.py", line 547, in browse
    return cls._browse(name=name, registry=registry, top_hash=top_hash)
  File "/usr/local/lib/python3.6/dist-packages/quilt3/packages.py", line 571, in _browse
    return cls._from_path(local_pkg_manifest)
  File "/usr/local/lib/python3.6/dist-packages/quilt3/packages.py", line 577, in _from_path
    pkg = cls._load(open_file)
  File "/usr/local/lib/python3.6/dist-packages/quilt3/packages.py", line 720, in _load
    for _ in readable_file:
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4791: ordinal not in range(128)
```

**Comment by sir-sigurd** [comment]
What's the output of this?
```python
import locale
print(locale.getpreferredencoding(False))
```

**Comment by saksham219** [comment]
@sir-sigurd 
`
>>> print(locale.getpreferredencoding(False))
ANSI_X3.4-1968
`

**Comment by sir-sigurd** [comment]
@saksham219 could you check if `quilt3==3.3.0rc1` works?
