### ISSUE TITLE
JSONDecodeError when removing package with quilt rm

### ISSUE THREAD

**Issue by mdyzma** [quiltdata/quilt#800]
## JSONDecodeError

In my case I am unable to remove any package using quilt CLI. Listing shows multiple packages (team and free plan user). When I type, i.e.:

```
$ quilt ls
/Users/michaldyzma/Library/Application Support/QuiltCli/quilt_packages
akarve/mnist                   latest               006edb89e4baf4521cceece46433412eef4b533631df4774be2133b3c5ba798f
```

Ween I try to remove it i get `JSONDecodeError`

```
$ quitl rm akarve/mnist
Remove akarve/mnist? (y/n) y
Traceback (most recent call last):
  File "/anaconda3/bin/quilt", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.6/site-packages/quilt/tools/main.py", line 365, in main
    func(**kwargs)
  File "/anaconda3/lib/python3.6/site-packages/quilt/tools/command.py", line 1208, in rm
    deleted = store.remove_package(team, owner, pkg)
  File "/anaconda3/lib/python3.6/site-packages/quilt/tools/store.py", line 282, in remove_package
    return self.prune(remove_objs)
  File "/anaconda3/lib/python3.6/site-packages/quilt/tools/store.py", line 375, in prune
    for pkg in self.iterpackages():
  File "/anaconda3/lib/python3.6/site-packages/quilt/tools/store.py", line 296, in iterpackages
    yield self.get_package(team, user, pkg, pkghash=hsh)
  File "/anaconda3/lib/python3.6/site-packages/quilt/tools/store.py", line 213, in get_package
    return json.load(contents_file, object_hook=decode_node)
  File "/anaconda3/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/anaconda3/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/anaconda3/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 70933 column 18 (char 3037711)
```

### Quilt version is:

```
$ quilt --version
quilt 2.9.15 (quilt-2.9.15-py3.6)
```

### My python is Anaconda:

```
$ conda info

     active environment : None
       user config file : /Users/michaldyzma/.condarc
 populated config files : /Users/michaldyzma/.condarc
          conda version : 4.5.12
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : /anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /anaconda3/pkgs
                          /Users/michaldyzma/.conda/pkgs
       envs directories : /anaconda3/envs
                          /Users/michaldyzma/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.12 requests/2.20.1 CPython/3.6.5 Darwin/18.2.0 OSX/10.14.2
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by mdyzma** [comment]
After removing all content of `/Users/michaldyzma/Library/Application Support/QuiltCli/quilt_packages
` problem is gone. 

Walk away message: It would be nice to have some mechanizm catching this kind of errors (lack of some metadata file i guess)
